title: "Sections"
description: |
  Sections should be used to convey information about the company and to lead the viewer to buy products.

patterns:
  simple-section:
    fields:
      - name: heading
        type: string
        example: "Jewelry with sophistication"
      - name: text
        type: string
        example: "Our necklaces are meant to suit all people. Chic pieces that are sure to dress up any outfit. All necklaces are crafted to last through constant wear, hold onto your jewelry longer."
    title: "Simple Section"
    description: |
      Simple section should be used when the section only includes text information and no buttons or links.
  section-button:
    fields:
      - name: heading
        type: string
        example: "Why shop J'Adorn"
      - name: text
        type: string
        example: "We take pride and care curating our collections and making our pieces. Each piece is unique and can be styled with any type of outfit. The materials we use are quality and won’t tarnish. Shop our new collections or browse our jewelry page for something that suits you."
      - name: button_text
        type: string
        example: "Shop now"
      - name: button_url
        type: url
        example: "/Shop now/"
    title: "Section with Buttons"
    description: |
      The section with buttons is to be used when the section requires buttons with links to lead the viewer to another area of the website. This can link to different categories of products and to other pages in general.
  product-section:
    fields:
      - name: image
        type: string
        example: "necklace.jpg"
      - name: button_text
        type: string
        example: "Add to Cart"
      - name: button_url
        type: url
        example: "/checkout/"
    title: "Product Section"
    description: |
      Product section should be used when the user selects a particular product, this provides a more detailed look at the product. This will be accompanied by a photo of the product.
  cart-total:
    title: "Cart Total"
    description: |
      Cart total section is used for the order summary on the checkout page. This is where the user will find price details of the product, and the final total due.
  product-cart:
    fields:
      - name: data
        type: object
        data:
          source: "site.products[3]"
      - name: button_text
        type: string
        example: "Remove from cart"
      - name: button_url
        type: url
        example: "/checkout/"
    title: "Product Cart"
    description: |
      Product Cart section should be used within the checkout page to summarize products added to cart.
  promo-banner:
    fields:
      - name: heading
        type: string
        example: "Blowout Prices on Beautiful Jewelry"
      - name: text
        type: string
        example: "Buy in bulk and save"
    title: "Promotional Banner"
    description: |
      Promotional Banner should be used when there is a sale or a promotional event.
  bulk-table:
    fields:
    title: "Bulk Table"
    description: |
      Bulk table should be used to demonstrate sales on buying bulk items usually found on the sale page.
  email-signup:
    fields:
      - name: heading
        type: string
        example: "Love our stuff?"
      - name: text
        type: string
        example: "Sign up for our newsletter to be the first to know about our deals and new products."
      - name: button_text
        type: string
        example: "Sign Up"
      - name: button_url
        type: url
        example: ""
