title: "Sections"
description: |
  Sections should be used to convey information about the company and to lead the viewer to buy products.

patterns:
  simple-section:
    title: "Simple Section"
    description: |
      Simple section should be used when the section only includes text information and no buttons or links.
  section-button:
    fields:
      - name: heading
        type: string
        example: "Why shop J'Adorn"
      - name: text
        type: string
        example: "We take pride and care curating our collections and making our pieces. Each piece is unique and can be styled with any type of outfit. The materials we use are quality and won’t tarnish. Shop our new collections or browse our jewelry page for something that suits you."
      - name: button_text
        type: string
        example: "Shop now"
      - name: button_url
        type: url
        example: "/Shop now/"
    title: "Section with Buttons"
    description: |
      The section with buttons is to be used when the section requires buttons with links to lead the viewer to another area of the website. This can link to different categories of products and to other pages in general.
  product-section:
    fields:
      - name: image
        type: string
        example: "necklace.jpg"
      - name: button_text
        type: string
        example: "Add to Cart"
      - name: button_url
        type: url
        example: "/Cart/"
    title: "Product Section"
    description: |
      Product section should be used when the user selects a particular product, this provides a more detailed look at the product. This will be accompanied by a photo of the product.
  cart-total:
    title: "Cart Total"
    description: |
      Cart total section is used for the order summary on the checkout page. This is where the user will find price details of the product, and the final total due.
