title: "Cards"
description: |
  Cards should be used to showcase images and call to actions.

patterns:
  product-card:
    fields:
      - name: image
        type: string
        example: "rings.jpg"
      - name: button_text
        type: string
        example: "Rings"
      - name: button_url
        type: url
        example: "/rings/"
    title: "Product"
    description: |
      This type of card is used as a link to go shop for a particular product. This card is used to denote specific groups of products.
  shop-new:
    fields:
      - name: heading
        type: string
        example: "Shop new"
      - name: text
        type: string
        example: "New pieces are added each month to keep our inventory fresh."
      - name: image
        type: string
        example: "layered-necklaces.jpg"
      - name: button_text
        type: string
        example: "Shop now"
      - name: button_url
        type: url
        example: "/Shop now/"
    title: "Shop New"
    description: |
      This card is used as a main banner for each page. The image spreads as wide as the screen and has a call to action promoting to shop the new collection.
  square-card:
    title: "Square Card"
    description: |
      This card is used as a product image with no text or buttons on top of it. This card showcases an image of the particular product and has a price listed below.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
  square-cards-product:
    title: "Square Card Products"
        description: |
          This arrangement of cards is used on the product information page to show different images of the product.
    fields:
      - name: image
        type: string
        example: "necklace-square.jpg"
